/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardEntryRouteImport } from './routes/dashboard-entry'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardEntryIndexRouteImport } from './routes/dashboard-entry/index'
import { Route as DashboardEntryLoginRouteImport } from './routes/dashboard-entry/login'

const DashboardEntryRoute = DashboardEntryRouteImport.update({
  id: '/dashboard-entry',
  path: '/dashboard-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEntryIndexRoute = DashboardEntryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEntryRoute,
} as any)
const DashboardEntryLoginRoute = DashboardEntryLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardEntryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard-entry': typeof DashboardEntryRouteWithChildren
  '/dashboard-entry/login': typeof DashboardEntryLoginRoute
  '/dashboard-entry/': typeof DashboardEntryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard-entry/login': typeof DashboardEntryLoginRoute
  '/dashboard-entry': typeof DashboardEntryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard-entry': typeof DashboardEntryRouteWithChildren
  '/dashboard-entry/login': typeof DashboardEntryLoginRoute
  '/dashboard-entry/': typeof DashboardEntryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard-entry'
    | '/dashboard-entry/login'
    | '/dashboard-entry/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard-entry/login' | '/dashboard-entry'
  id:
    | '__root__'
    | '/'
    | '/dashboard-entry'
    | '/dashboard-entry/login'
    | '/dashboard-entry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardEntryRoute: typeof DashboardEntryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard-entry': {
      id: '/dashboard-entry'
      path: '/dashboard-entry'
      fullPath: '/dashboard-entry'
      preLoaderRoute: typeof DashboardEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-entry/': {
      id: '/dashboard-entry/'
      path: '/'
      fullPath: '/dashboard-entry/'
      preLoaderRoute: typeof DashboardEntryIndexRouteImport
      parentRoute: typeof DashboardEntryRoute
    }
    '/dashboard-entry/login': {
      id: '/dashboard-entry/login'
      path: '/login'
      fullPath: '/dashboard-entry/login'
      preLoaderRoute: typeof DashboardEntryLoginRouteImport
      parentRoute: typeof DashboardEntryRoute
    }
  }
}

interface DashboardEntryRouteChildren {
  DashboardEntryLoginRoute: typeof DashboardEntryLoginRoute
  DashboardEntryIndexRoute: typeof DashboardEntryIndexRoute
}

const DashboardEntryRouteChildren: DashboardEntryRouteChildren = {
  DashboardEntryLoginRoute: DashboardEntryLoginRoute,
  DashboardEntryIndexRoute: DashboardEntryIndexRoute,
}

const DashboardEntryRouteWithChildren = DashboardEntryRoute._addFileChildren(
  DashboardEntryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardEntryRoute: DashboardEntryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
